# Generated by Django 2.2.15 on 2020-09-26 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('barcode', models.IntegerField()),
                ('dispatch', models.CharField(choices=[(1, 'RETURN'), (2, 'TAKE')], max_length=2)),
                ('added_at', models.DateField(auto_now_add=True, null=True)),
                ('editedAt', models.DateField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
