# Generated by Django 2.2.15 on 2020-09-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='dispatch',
        ),
        migrations.AddField(
            model_name='artikel',
            name='location',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='artikel',
            name='status',
            field=models.CharField(choices=[('RETURN', 'RETURN'), ('TAKE', 'TAKE')], default='RETURN', max_length=25),
        ),
    ]
