# Generated by Django 2.2.15 on 2020-09-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200926_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='location',
            field=models.CharField(default='In Storage', max_length=100),
        ),
    ]
